mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password)
}

mutation createProduct($data: ProductInput) {
  createProduct(data: $data)
}

mutation updateProduct($updateProductId: Int!, $data: ProductInput) {
  updateProduct(id: $updateProductId, data: $data)
}

mutation updateCategory($updateCategoryId: Int!, $data: CategoryInput, $isActive: Boolean) {
  updateCategory(id: $updateCategoryId, data: $data, isActive: $isActive)
}

mutation createCategory($data: CategoryInput) {
  createCategory(data: $data)
}

mutation createOrder($data: OrderInput) {
  createOrder(data: $data)
}

mutation addOrderItem($orderId: Int!, $data: CartItemInput) {
  addOrderItem(orderId: $orderId, data: $data)
}

mutation markOrderItemStatus($markOrderItemStatusId: Int!, $status: StatusOrderItem) {
  markOrderItemStatus(id: $markOrderItemStatusId, status: $status)
}

mutation increaseOrderItem($increaseOrderItemId: Int!) {
  increaseOrderItem(id: $increaseOrderItemId)
}

mutation decreaseOrderItem($decreaseOrderItemId: Int!) {
  decreaseOrderItem(id: $decreaseOrderItemId)
}

mutation changeOrderStatus($data: ChangeOrderInput) {
  changeOrderStatus(data: $data)
}

mutation generateTokenOrder($set: Int!) {
  generateTokenOrder(set: $set)
}

mutation verifyOtpOrder($token: String!, $code: String!) {
  verifyOtpOrder(token: $token, code: $code)
}

mutation signatureOrder($signatureOrderId: Int!, $password: String!, $username: String!, $userId: Int!) {
  signatureOrder(id: $signatureOrderId, password: $password, username: $username, userId: $userId)
}

mutation updateSetting($option: String, $value: String) {
  updateSetting(option: $option, value: $value)
}

mutation generateTableSet($sets: Int!) {
  generateTableSet(sets: $sets)
}

mutation createDelivery($data: DeliveryInput) {
  createDelivery(data: $data)
}

mutation updateDelivery($updateDeliveryId: Int!, $data: DeliveryInput) {
  updateDelivery(id: $updateDeliveryId, data: $data)
}

mutation createUser($data: UserInput) {
  createUser(data: $data)
}

mutation updateUser($id: Int!, $data: UserInput) {
  updateUser(id: $id, data: $data)
}

mutation createPosition($name: String!) {
  createPosition(name: $name)
}

mutation updatePosition($name: String!, $updatePositionId: Int!) {
  updatePosition(name: $name, id: $updatePositionId)
}

mutation createBank($name: String!, $phone: String) {
  createBank(name: $name, phone: $phone)
}

mutation updateBank($updateBankId: Int!, $name: String!, $phone: String) {
  updateBank(id: $updateBankId, name: $name, phone: $phone)
}

mutation checkAttendance($userId: Int!, $date: String!) {
  checkAttendance(userId: $userId, date: $date)
}

mutation createShift($data: ShiftInput) {
  createShift(data: $data)
}

mutation updateShift($updateShiftId: Int!, $expected: Boolean, $data: ShiftInput) {
  updateShift(id: $updateShiftId, expected: $expected, data: $data)
}

mutation peopleInOrder($peopleInOrderId: Int!, $count: Int!) {
  peopleInOrder(id: $peopleInOrderId, count: $count)
}

mutation createLeave($userId: Int!, $data: LeaveInput) {
  createLeave(userId: $userId, data: $data)
}

mutation updateLeave($updateLeaveId: Int!, $data: LeaveInput) {
  updateLeave(id: $updateLeaveId, data: $data)
}

mutation updateLeaveStatus($updateLeaveStatusId: Int!, $status: LeaveStatus) {
  updateLeaveStatus(id: $updateLeaveStatusId, status: $status)
}

mutation createOverTime($userId: Int!, $data: OverTimeInput) {
  createOverTime(userId: $userId, data: $data)
}

mutation updateOverTime($updateOverTimeId: Int!, $data: OverTimeInput) {
  updateOverTime(id: $updateOverTimeId, data: $data)
}

mutation updateOverTimeStatus($updateOverTimeStatusId: Int!, $status: OverTimeStatus) {
  updateOverTimeStatus(id: $updateOverTimeStatusId, status: $status)
}

mutation updateStatusProduct($updateStatusProductId: Int!, $status: STATUS_PRODUCT!) {
  updateStatusProduct(id: $updateStatusProductId, status: $status)
}

mutation addDiscountOrder($addDiscountOrderId: Int!, $discount: Float!) {
  addDiscountOrder(id: $addDiscountOrderId, discount: $discount)
}

mutation setTypePaymentOrder($setTypePaymentOrderId: Int!, $bankType: String, $currency: String, $bankId: Int) {
  setTypePaymentOrder(id: $setTypePaymentOrderId, bankType: $bankType, currency: $currency, bankId: $bankId)
}

mutation swapOrderTable($orderId: Int!, $table: String) {
  swapOrderTable(orderId: $orderId, table: $table)
}

mutation checkProductCode($code: String!) {
  checkProductCode(code: $code)
}

mutation createHoliday($data: HolidayInput) {
  createHoliday(data: $data)
}

mutation updateHoliday($updateHolidayId: Int!, $data: HolidayInput) {
  updateHoliday(id: $updateHolidayId, data: $data)
}

mutation createOrderSchedule($data: OrderScheduleInput) {
  createOrderSchedule(data: $data)
}

mutation updateOrderSchedule($updateOrderScheduleId: Int!, $data: OrderScheduleInput) {
  updateOrderSchedule(id: $updateOrderScheduleId, data: $data)
}

mutation deleteOrderSchedule($deleteOrderScheduleId: Int!) {
  deleteOrderSchedule(id: $deleteOrderScheduleId)
}

mutation resetPassword($username: String!, $oldPassowrd: String!, $password: String!) {
  resetPassword(username: $username, oldPassowrd: $oldPassowrd, password: $password)
}

mutation setItemShowOn($productId: Int!, $skuId: Int, $status: String) {
  setItemShowOn(productId: $productId, skuId: $skuId, status: $status)
}
